
services:
  users-db:
    image: postgres:16
    container_name: users-db
    environment:
      POSTGRES_DB: users-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3285
    ports:
      - "5433:5432"
    volumes:
      - users_pgdata:/var/lib/postgresql/data
    networks:
      - inno-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  products-db:
    image: postgres:16
    container_name: products-db
    environment:
      POSTGRES_DB: products-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3285
    ports:
      - "5434:5432"
    volumes:
      - products_pgdata:/var/lib/postgresql/data
    networks:
      - inno-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  user-service:
    build:
      context: .
      dockerfile: ./InnoShop.UserManager/InnoShop.UserManager.WebAPI/Dockerfile
    container_name: user-service
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=users-db;Database=UserManager;User Id=postgres;Password=3285;"
      Jwt__Key: "d5a372c4dc137ba5e0bb667ea5f65222dc3fd9234aa684248d5224f33f63e22d"
      Jwt__Issuer: "InnoShop.UserManager"
      Jwt__Audience: "InnoShop.ProductManagment"
      Jwt__AccessTokenLifetimeMinutes: "30"
      Smtp__Host: "smtp.gmail.com"
      Smtp__Port: "587"
      Smtp__FromAddress: "c7673751@gmail.com"
      Smtp__Password: "fybmlxxbjhdfizsz"
      AppSettings__FrontendUrl: "http://localhost:7155"
      AppSettings__BackendUrl: "https://localhost:7155"
      PasswordResetTokenSettings__ExpireMinutes: "15"
      ProductServiceSettings__BaseAddress: "https://product-service:7156"
      ProductServiceSettings__HeaderName: "ProductServiceKey"
      ProductServiceSettings__ServiceKey: "7f368aaee5b94d3517696623a8a2e364a977ebaf09c4a41c8fd35b979094eec47"
    ports:
      - "7155:80"
    networks:
      - inno-net
        
  product-service:
    build:
      context: .
      dockerfile: ./InnoShop.ProductManagment/InnoShop.ProductManagment.WebApi/Dockerfile
    container_name: product-service
    depends_on:
      products-db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=products-db;Database=ProductManagement;User Id=postgres;Password=3285;"
      Jwt__Key: "d5a372c4dc137ba5e0bb667ea5f65222dc3fd9234aa684248d5224f33f63e22d"
      Jwt__Issuer: "InnoShop.UserManager"
      Jwt__Audience: "InnoShop.ProductManagment"
      Jwt__AccessTokenLifetimeMinutes: "30"
      ProductServiceOptions__HeaderName: "ProductServiceKey"
      ProductServiceOptions__ServiceKey: "7f368aaee5b94d3517696623a8a2e364a977ebaf09c4a41c8fd35b979094eec47"
    ports:
      - "7156:80"
    networks:
      - inno-net

volumes:
  users_pgdata:
  products_pgdata:

networks:
  inno-net: